# Generated by Django 5.0.6 on 2025-03-02 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_gallerycategory_galleryimage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TrainingSkill",
            new_name="Skill",
        ),
        migrations.RenameModel(
            old_name="TrainingCategory",
            new_name="SkillCategory",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
    ]
