# Generated by Django 5.0.6 on 2025-03-02 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_skillcategory_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skillcategory",
            name="image",
        ),
    ]
