# Generated by Django 5.0.6 on 2025-03-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_skillcategory_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillcategory",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to="training_images/"
            ),
        ),
    ]
